server:
  port: 8082
spring:
  application:
    name: yes-camunda-history
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  jackson:
    default-property-inclusion: non_empty
  web:
    resources:
      add-mappings: false
  liquibase:
    change-log: "classpath:org/camunda/bpm/engine/db/liquibase/camunda-changelog.xml"
camunda:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      pool-name: camunda-db-cp
      auto-commit: false
      minimum-idle: 1
      maximum-pool-size: 10
      idleTimeout: 250000
      maxLifetime: 3600000
      connectionTimeout: 60000
      connection-test-query: SELECT 1
      data-source-properties:
        cacheServerConfiguration: true
  bpm:
    admin-user:
      id: demo
      first-name: demo
      last-name: demo
      password: demo
    process-engine-name: yesCamundaHistoryService
    filter:
      create: All Tasks
    job-execution:
      deployment-aware: true
    default-serialization-format: "application/json"
    webapp:
      application-path: "/camunda-history/"
    database:
      type: postgres
